# Generated by Django 5.2.7 on 2025-10-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0002_remove_movie_director_remove_movie_release_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='movie',
            name='title',
            field=models.CharField(default='Untitled', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default=1900),
        ),
    ]
